name: "Lint, Build & Test (Go)"

on:
  push:
    branches:
      - main  
    paths:
      - "**.go"
  pull_request:
    branches:
      - main
    paths:
      - "**.go"

jobs:
  lint-build-test:
    name: "Run lint, build, test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-go@v2"
        with:
          go-version: "1.17.1"
      - name: "vet"
        run: "go vet ./..."
      - name: "build"
        run: "go build ."
      - name: "test"
        run: "go test -v ./..."
